"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-07-10 11:09:30.645657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BASELINE_TABLES = {
    "channels",
    "entities",
    "agent_beliefs",
    "agent_needs",
    "events",
    "locations",
    "messages",
    "ownership",
    "physical_state",
    "relations",
    "schedules",
    "agent_intents",
    "conversation_threads",
    "read_receipts",
}


def upgrade() -> None:
    """Upgrade schema."""
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    existing_baseline = existing_tables & BASELINE_TABLES
    if existing_baseline == BASELINE_TABLES:
        return
    if existing_baseline:
        missing = sorted(BASELINE_TABLES - existing_baseline)
        raise RuntimeError(
            "Cannot adopt partially initialized Kami schema; missing tables: "
            + ", ".join(missing)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('subscribers', sa.JSON(), nullable=True),
    sa.Column('medium_properties', sa.JSON(), nullable=True),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('archetype', sa.JSON(), nullable=True),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.Column('created_by_event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_kind', ['kind'], unique=False)

    op.create_table('agent_beliefs',
    sa.Column('belief_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.Column('believed_value', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('belief_id')
    )
    with op.batch_alter_table('agent_beliefs', schema=None) as batch_op:
        batch_op.create_index('ix_beliefs_agent', ['agent_id'], unique=False)

    op.create_table('agent_needs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('need', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('valid_until_tick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_needs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_needs_current', ['agent_id', 'need', 'valid_until_tick'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('kami_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('causes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['kami_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_kami_tick', ['kami_id', 'tick'], unique=False)
        batch_op.create_index('ix_events_tick', ['tick'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('kami_id', sa.String(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('valid_until_tick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['kami_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_locations_entity_current', ['entity_id', 'valid_until_tick'], unique=False)
        batch_op.create_index('ix_locations_kami_current', ['kami_id', 'valid_until_tick'], unique=False)

    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at_tick', sa.Integer(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_channel_tick', ['channel_id', 'sent_at_tick'], unique=False)

    op.create_table('ownership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('valid_until_tick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ownership', schema=None) as batch_op:
        batch_op.create_index('ix_ownership_entity_current', ['entity_id', 'valid_until_tick'], unique=False)

    op.create_table('physical_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('valid_until_tick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physical_state', schema=None) as batch_op:
        batch_op.create_index('ix_physstate_entity_attr_current', ['entity_id', 'attribute', 'valid_until_tick'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_entity', sa.String(), nullable=False),
    sa.Column('to_entity', sa.String(), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=False),
    sa.Column('weight', sa.JSON(), nullable=True),
    sa.Column('since_tick', sa.Integer(), nullable=False),
    sa.Column('valid_until_tick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_entity'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['to_entity'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index('ix_relations_from_type_current', ['from_entity', 'rel_type', 'valid_until_tick'], unique=False)

    op.create_table('schedules',
    sa.Column('schedule_id', sa.String(), nullable=False),
    sa.Column('fires_at_tick', sa.Integer(), nullable=False),
    sa.Column('kami_id', sa.String(), nullable=False),
    sa.Column('event_template', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['kami_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_tick', ['fires_at_tick'], unique=False)

    op.create_table('agent_intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('kami_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_event_id', sa.String(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('pressure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['kami_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['result_event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    with op.batch_alter_table('agent_intents', schema=None) as batch_op:
        batch_op.create_index('ix_agent_intents_agent_tick', ['agent_id', 'tick'], unique=False)
        batch_op.create_index('ix_agent_intents_kami_tick', ['kami_id', 'tick'], unique=False)
        batch_op.create_index('ix_agent_intents_status', ['status'], unique=False)

    op.create_table('conversation_threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('kami_id', sa.String(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tension', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('last_event_id', sa.String(), nullable=True),
    sa.Column('last_tick', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('open_question', sa.Text(), nullable=True),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kami_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['last_event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    with op.batch_alter_table('conversation_threads', schema=None) as batch_op:
        batch_op.create_index('ix_threads_kami_status', ['kami_id', 'status'], unique=False)
        batch_op.create_index('ix_threads_last_tick', ['last_tick'], unique=False)

    op.create_table('read_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('read_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'agent_id', name='uq_read_receipt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_receipts')
    with op.batch_alter_table('conversation_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_last_tick')
        batch_op.drop_index('ix_threads_kami_status')

    op.drop_table('conversation_threads')
    with op.batch_alter_table('agent_intents', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_intents_status')
        batch_op.drop_index('ix_agent_intents_kami_tick')
        batch_op.drop_index('ix_agent_intents_agent_tick')

    op.drop_table('agent_intents')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_tick')

    op.drop_table('schedules')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index('ix_relations_from_type_current')

    op.drop_table('relations')
    with op.batch_alter_table('physical_state', schema=None) as batch_op:
        batch_op.drop_index('ix_physstate_entity_attr_current')

    op.drop_table('physical_state')
    with op.batch_alter_table('ownership', schema=None) as batch_op:
        batch_op.drop_index('ix_ownership_entity_current')

    op.drop_table('ownership')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_channel_tick')

    op.drop_table('messages')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_kami_current')
        batch_op.drop_index('ix_locations_entity_current')

    op.drop_table('locations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_tick')
        batch_op.drop_index('ix_events_kami_tick')

    op.drop_table('events')
    with op.batch_alter_table('agent_needs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_needs_current')

    op.drop_table('agent_needs')
    with op.batch_alter_table('agent_beliefs', schema=None) as batch_op:
        batch_op.drop_index('ix_beliefs_agent')

    op.drop_table('agent_beliefs')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_kind')

    op.drop_table('entities')
    op.drop_table('channels')
    # ### end Alembic commands ###
