"""add simulations registry

Revision ID: 0002_simulations
Revises: 0001_baseline
Create Date: 2026-07-10 11:10:20.622240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_simulations'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if sa.inspect(op.get_bind()).has_table("simulations"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('db_url', sa.String(), nullable=True),
    sa.Column('db_path', sa.String(), nullable=True),
    sa.Column('graph_path', sa.String(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index('ix_simulations_active', ['is_active'], unique=False)
        batch_op.create_index('ix_simulations_updated', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if not sa.inspect(op.get_bind()).has_table("simulations"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index('ix_simulations_updated')
        batch_op.drop_index('ix_simulations_active')

    op.drop_table('simulations')
    # ### end Alembic commands ###
